### ISSUE TITLE
Error: If encoding is specified then the first argument must be a string

### ISSUE THREAD

**Issue by sc0rp10** [node-freight/freight-server#35]
```
buffer.js:69
      throw new Error(
      ^

Error: If encoding is specified then the first argument must be a string
    at new Buffer (buffer.js:69:13)
    at Readable.<anonymous> (/private/tmp/freight-server/node_modules/archiver/lib/util/index.js:32:15)
    at emitNone (events.js:91:20)
    at Readable.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

Fires at `freight create -u=http://127.0.0.1:8872/`

```
$ node -v
v6.3.1
```

**Comment by andrewwakeling** [comment]
I hit this problem too. Using node v.4.6.x seems to fix this problem. Maybe .nvmrc could be beneficial here?
